---
kind: pipeline
type: docker
name: ckube

workspace:
  base: /go
  path: src/backend

#concurrency:
#  limit: 1

steps:
  - name: unit test
    image: golang:1.14-alpine
    pull: if-not-exists
    volumes:
      - name: go-cache
        path: /go/pkg
    environment:
      GOPROXY: https://goproxy.io
      GO111MODULE: on
      GOCACHE: /go/pkg/.cache
    commands:
      - GOOS=linux CGO_ENABLED=0 go test ./...

  - name: update
    image: curlimages/curl
    pull: if-not-exists
    environment:
      GITLAB_TOKEN:
        from_secret: gitlab_token
    commands:
      - 'curl https://gitlab.daocloud.cn/api/v4/projects/mesh%2Fdsm/repository/submodules/ckube -H "PRIVATE-TOKEN: $GITLAB_TOKEN"  -X PUT -d "branch=${DRONE_BRANCH}&commit_sha=${DRONE_COMMIT_SHA}&commit_message=auto update ckube submodule@$(date)"'
    when:
      branch:
        - develop

  - name: update fix and feature branch
    image: curlimages/curl
    pull: if-not-exists
    environment:
      GITLAB_TOKEN:
        from_secret: gitlab_token
    commands:
      - 'curl https://gitlab.daocloud.cn/api/v4/projects/mesh%2Fdsm/repository/branches -H "PRIVATE-TOKEN: $GITLAB_TOKEN"  -X POST -d "branch=${DRONE_BRANCH}&ref=develop"'
      - 'curl https://gitlab.daocloud.cn/api/v4/projects/mesh%2Fdsm/repository/submodules/ckube -H "PRIVATE-TOKEN: $GITLAB_TOKEN"  -X PUT -d "branch=${DRONE_BRANCH}&commit_sha=${DRONE_COMMIT_SHA}&commit_message=auto update ckube submodule@$(date)"'
    when:
      branch:
        - feature/*
        - fix/*

volumes:
  - name: go-cache
    host:
      path: /daocloud/drone/cache/mesh/go
  - name: docker-cache
    host:
      path: /daocloud/drone/cache/mesh/docker/ckube

  - name: docker-sock
    host:
      path: /var/run/docker.sock
